/**
 * Rights Microservice
 * Mockable microservice to manage user rights, user groups and group rights
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RightDTO {
    createdBy?: string;
    creationDate?: string;
    expirationDate?: string;
    rightDescription?: string;
    rightId?: number;
    rightName?: string;
    system?: string;
    ticket?: string;
    allocated?: string;
}
