/**
 * Rights Microservice
 * Mockable microservice to manage user rights, user groups and group rights
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDTO { 
    active?: number;
    createdBy?: string;
    creationDate?: string;
    deleted?: number;
    displayName?: string;
    userId?: number;
    userType?: string;
}